### ISSUE TITLE
Mapped value is not correctly shown in sub-label

### ISSUE THREAD

**Issue by hypetsch** [stefan-torstensson/openhab-remote#2]
I have the following setup:
- item
`Number BsbParameter700NumberValue  { channel="bsblan:parameter:heating:p700:number-value" }`
- sitemap
`Selection item=BsbParameter700NumberValue label="Betriebsart" mappings=[0="Schutzbetrieb", 1="Automatik", 2="Reduziert", 3="Komfort"] icon="heating"`

As you can see on the following screenshot the current version shows an incorrect/unmapped value:
![image](https://user-images.githubusercontent.com/16302578/73017034-53428c80-3e1f-11ea-8da4-da055bb35617.png)

As far as I have analyzed its because openhab for some reason sends `Betriebsart [1.0 °C]` as label which causes the current mapping implementation to fail. See this screenshot:
![image](https://user-images.githubusercontent.com/16302578/73018703-7458ac80-3e22-11ea-9491-d19beea4393f.png)

I have then experimentally changed the function [stateLabel()](https://github.com/stefan-torstensson/openhab-remote/blob/d88a28c7bea0e46d705471837497c066b98dc20b/src/ui/openhab/widgets/widget-control.ts#L28) in `widget-control.ts` to
```ts
    get stateLabel(): string {
        const {state} = parseLabel(this.widget.label);
        if (state) {
            const mapping = this.widget.mappings.find(m => m.command === this.widget.item.state);
            return mapping ? mapping.label : state;
        }
        return null;
    }
```
in order to use the actual state value provided by openhab rather than the parsed one. This results in the expected output:
![image](https://user-images.githubusercontent.com/16302578/73017517-470aff00-3e20-11ea-9b64-efe68206dfe5.png)

Anyways I think this might not be the correct fix as I assume that maybe the mapping (if configured) should be done first (with the state value provided by openhab) and the result of `parseLabel()` should only be used when no mapped value is available?

Would be great to have this fixed or am I missing something?

**Comment by stefan-torstensson** [comment]
You're probably on the right path. I had another look at the Basic UI implementation and it seems the raw state is used rather than the value from the label when a mapping exists.
The assumption here was that the state value is included in the label and if it corresponds to a mapping, then the mapping is used. This gives the possibility to show a different value in the label. But that's probably not a desired use case when there are mappings available.

When digging a bit deeper there are additional issues with the mappings. If the item has a commandDescription those mappings should be used when there is no explicit mapping in the widget so it might be that the re-use of the SwitchControl was a bit simplistic in this case.
I'll have to investigate a bit further.

For the time beeing you can probably work around it by adding `[%d]` or `[%.0f]` to the label in your sitemap, i.e. `label="Betriebsart [%d]"`

**Comment by hypetsch** [comment]
You are right, using `label="Betriebsart [%d]"` works around the issue.
